#%RAML 0.8
---
title: API
baseUri: https://restkit.loxal.net/
version: latest
protocols: [ HTTPS ]
mediaType: application/json

traits:
  - !include //api.cf.hybris.com/patterns/v1/trait-app-aware.yaml

schemas:
  - id: !include schema/host.json
  - error-message: !include //api.cf.hybris.com/patterns/v1/schema-error-message.json

securitySchemes:
  - !include //api.cf.hybris.com/patterns/v1/security-schema-basic.yaml

/whois:
  get:
    is: [ appAware ]
    description: Retrieve host information
    responses:
      200:
        description: Success
        body:
          schema: host
      503:
        description: Failure
        body:
          schema: error-message

/resolve-ip-address:
  get:
    queryParameters:
      hostName:
        description: domain name
        type: string
        required: true
        example: example.com
    is: [ appAware ]
    description: Retrieve host information
    responses:
      200:
        description: Success
        body:
          schema: host
      503:
        description: Failure
        body:
          schema: error-message

/group:
  post:
    is: [ appAware ]
    body:
      example: |
        {
          "name": "My series of polls for e.g. a planning poker game",
          "entityReferences": ["//soa.example.com/resource/id-1", "//soa.example.com/resource/id-2"]
        }
  /{id}:
    get:
      is: [ appAware ]
    put:
      is: [ appAware ]
    delete:
      is: [ appAware ]

/ballot/poll:
  post:
    is: [ appAware ]
    body:
      example: |
        {
          "question": "What is the meaning of life?",
          "options": ["42", "23", "None", "NA"]
        }
  /{id}:
    get:
      is: [ appAware ]
    put:
      is: [ appAware ]
    delete:
      is: [ appAware ]

/ballot/vote:
  post:
    is: [ appAware ]
    body:
      example: |
        {
          "referencePoll": "http://host/ballot/pool/53b9ea00dc6eb5ee7546aeac",
          "correctAnswers": [ 1, 3 ]
        }
  /{id}:
    get:
      is: [ appAware ]
    put:
      is: [ appAware ]
    delete:
      is: [ appAware ]
