FROM jetty:9
#FROM appengine.gcr.io/gcloud/rest-kit-loxal.default.1-5-5
#FROM appengine.gcr.io/gcloud/coreos-stable-766-5-0-v20151105

MAINTAINER Alexander Orlov <alexander.orlov@loxal.net>

ADD . webapps/ROOT
